# Generated by Django 4.0 on 2022-01-02 20:09

import api.enums
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('created', models.DateField()),
            ],
            options={
                'db_table': 'areas',
                'ordering': ['name', 'created'],
            },
        ),
        migrations.CreateModel(
            name='Journal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('descrpiption', models.TextField(max_length=500)),
                ('created', models.DateTimeField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.user')),
            ],
            options={
                'db_table': 'journals',
                'ordering': ['name', 'created'],
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dob', models.DateField()),
                ('gender', models.CharField(choices=[(api.enums.Gender['FEMALE'], 'female'), (api.enums.Gender['MALE'], 'male'), (api.enums.Gender['PRIVACY'], 'preffered not to say')], default=api.enums.Gender['PRIVACY'], max_length=10)),
                ('avatar', models.ImageField(upload_to='')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='auth.user')),
            ],
            options={
                'db_table': 'user_profiles',
            },
        ),
        migrations.CreateModel(
            name='MoodLogs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mood', models.CharField(choices=[(api.enums.MOODS['HAPPY'], 'happy'), (api.enums.MOODS['SAD'], 'sad'), (api.enums.MOODS['NONE'], 'none'), (api.enums.MOODS['LOVE'], 'love'), (api.enums.MOODS['ANGRY'], 'angry')], default=api.enums.MOODS['NONE'], max_length=10)),
                ('created', models.DateTimeField()),
                ('note', models.TextField(default='')),
                ('journal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.journal')),
            ],
            options={
                'db_table': 'mood_logs',
                'ordering': ['created'],
            },
        ),
        migrations.CreateModel(
            name='Habits',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('notion', models.CharField(choices=[(api.enums.NOTIONS['GOOD'], 'good'), (api.enums.NOTIONS['BAD'], 'bad')], default=api.enums.NOTIONS['GOOD'], max_length=10)),
                ('time_preffered', models.CharField(choices=[(api.enums.TIME_OF_DAY['MRNG'], 'morning'), (api.enums.TIME_OF_DAY['AFN'], 'afternoon'), (api.enums.TIME_OF_DAY['EVE'], 'evening'), (api.enums.TIME_OF_DAY['ALL'], 'all')], default=api.enums.TIME_OF_DAY['ALL'], max_length=20)),
                ('created', models.DateTimeField()),
                ('completed', models.IntegerField(default=0)),
                ('skipped', models.IntegerField(default=0)),
                ('failed', models.IntegerField(default=0)),
                ('streak', models.IntegerField(default=0)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.area')),
                ('journal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.journal')),
            ],
            options={
                'db_table': 'habits',
                'ordering': ['name', 'created'],
            },
        ),
        migrations.CreateModel(
            name='HabitLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField()),
                ('count_a_day', models.IntegerField(default=1)),
                ('status', models.CharField(choices=[(api.enums.LOG_STATUS['COMPLETED'], 'completed'), (api.enums.LOG_STATUS['FAIL'], 'fail'), (api.enums.LOG_STATUS['SKIP'], 'skip')], max_length=10)),
                ('notes', models.TextField(default='')),
                ('habit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.habits')),
            ],
            options={
                'db_table': 'habit_logs',
            },
        ),
    ]
