# Generated by Django 4.0 on 2022-01-02 20:16

import api.enums
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='gender',
            field=models.CharField(choices=[(api.enums.Gender['FEMALE'], 'Female'), (api.enums.Gender['MALE'], 'Male'), (api.enums.Gender['PRIVACY'], 'Preffered not to say')], default=api.enums.Gender['PRIVACY'], max_length=10),
        ),
    ]
