# Generated by Django 4.0 on 2022-01-02 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_remove_userprofile_gender'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='habitlog',
            name='count_a_day',
        ),
        migrations.AddField(
            model_name='habits',
            name='count_a_day',
            field=models.IntegerField(default=1),
        ),
    ]
