# Generated by Django 4.0 on 2022-01-03 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_remove_habitlog_count_a_day_habits_count_a_day'),
    ]

    operations = [
        migrations.AlterField(
            model_name='habitlog',
            name='time',
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name='habits',
            name='created',
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name='journal',
            name='created',
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name='moodlogs',
            name='created',
            field=models.DateTimeField(db_index=True),
        ),
    ]
